# Generated by Django 2.1.3 on 2018-11-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='user_from',
            new_name='user_form',
        ),
    ]
